services:
  restheart:
    image: softinstigate/restheart:latest
    environment:
      RHO: >
          /mclient/connection-string->"mongodb://mongodb1:27017/?replicaSet=rs0";
          /http-listener/host->"0.0.0.0";
    volumes:
      - $PWD/config/restheart.yml:/opt/restheart/etc/overrides.yml
    depends_on:
      mongodb1:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: [ "-o", "/opt/restheart/etc/overrides.yml" ]

  mongodb1:
    image: mongo:7.0
    command: [ "--bind_ip_all", "--replSet", "rs0" ]
    env_file:
      - path: $PWD/.env
        required: true
    volumes:
      - $DATA_STORE:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb1:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - $PWD/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  dumper:
    build: ./image_stream_dumper
    links:
      - restheart
      - mosquitto
    env_file:
      - path: $PWD/.env
        required: true
    environment:
      - RESTHEART_ENDPOINT=http://restheart:8080
      - CAM_STREAMING_URL=http://${GRIPPER_HOST}
      - MQTT_BROKER_URL=mosquitto
      - PYTHONUNBUFFERED=1
    command: /src/.venv/bin/dumper

  dynamics:
    build: ./arm_dynamics
    ports:
      - 8003:8000
    env_file:
      - path: $PWD/.env
        required: true
    environment:
      - MQTT_BROKER_URL=mosquitto
      - MOONRAKER_URL=ws://${KLIPPER_HOST}/websocket
    command: poetry run -- fastapi run src/main.py

